name = "NetProbe"
uuid = "c3d4e5f6-7890-12ab-cdef-333333333333"
authors = ["bad-antics <bad-antics@users.noreply.github.com>"]
version = "1.0.0"

[deps]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
